version: '3.7'

services:
  web:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    hostname: web
    privileged: true
    volumes:
      - ".:/usr/src/app/"
      - "./saml:/usr/src/app/turnpike/saml"
      - "./dev-backends.yml:/etc/turnpike/backends.yml"
    networks:
      mynet:
        aliases:
          - web
  nginx:
    build: ./nginx
    ports:
      - 443:8443
    depends_on:
      - web
    hostname: nginx
    volumes:
      - "./dev-backends.yml:/etc/turnpike/backends.yml"
      - "./nginx/certs:/etc/nginx/certs"
    networks:
      mynet:
        aliases:
          - nginx
    environment:
      NGINX_LISTEN: 8443 ssl
      NGINX_SERVER_NAME: nginx
      FLASK_SERVICE_URL: http://web:5000
      FLASK_SERVER_NAME: ${SERVER_NAME}
      NGINX_SSL_CONFIG: |
       ssl_certificate certs/cert.pem;
       ssl_certificate_key certs/key.pem;
  redis:
    image: redis:6
    hostname: redis
    networks:
      mynet:
        aliases:
          - redis
  echo-server:
    image: jmalloc/echo-server:latest
    hostname: echo-server
    ports:
      - 8080:8080
    networks:
      mynet:
        aliases:
          - echo-server
    environment:
      PORT: 8080
networks:
  mynet:
